name: Twitch Watch Streak Tracker

on:
  schedule:
    # Запуск каждые 2 часа (чтобы скрипт успевал просмотреть все каналы)
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest
    timeout-minutes: 120 # Даем скрипту до 60 минут на обход всех каналов
    permissions:
      contents: write

    steps:
      - name: Чтение репозитория
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка Playwright и браузеров
        run: |
          pip install playwright requests
          playwright install chromium
          playwright install-deps

      - name: Запуск автокликера Twitch
        env:
          TWITCH_AUTH_TOKEN: ${{ secrets.TWITCH_AUTH_TOKEN }}
        run: python parse_streaks.py

      - name: Сохранение данных в data.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update Twitch watch streaks [skip ci]" || exit 0
          git push
